"""add is_dynamic parameter

Revision ID: 0af1d5ef66e6
Revises: 23b32d94e1d8
Create Date: 2025-05-10 15:22:36.351900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af1d5ef66e6'
down_revision: Union[str, None] = '23b32d94e1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('is_dynamic', sa.Boolean(), nullable=True))
    op.drop_constraint('_specialization_grade_uc', 'roadmaps', type_='unique')
    op.create_unique_constraint('_specialization_grade_dynamic_uc', 'roadmaps', ['specialization', 'grade', 'is_dynamic'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_specialization_grade_dynamic_uc', 'roadmaps', type_='unique')
    op.create_unique_constraint('_specialization_grade_uc', 'roadmaps', ['specialization', 'grade'])
    op.drop_column('roadmaps', 'is_dynamic')
    # ### end Alembic commands ###
