"""add specialization into user

Revision ID: 23b32d94e1d8
Revises: c00adf1ec998
Create Date: 2025-05-04 20:09:02.824255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b32d94e1d8'
down_revision: Union[str, None] = 'c00adf1ec998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('specialization', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'specialization')
    # ### end Alembic commands ###
