"""add hh_id to Vacancy

Revision ID: 463d34bcefa6
Revises: 0af1d5ef66e6
Create Date: 2025-06-03 21:54:44.166413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463d34bcefa6'
down_revision: Union[str, None] = '0af1d5ef66e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('hh_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'vacancies', ['hh_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='unique')
    op.drop_column('vacancies', 'hh_id')
    # ### end Alembic commands ###
