"""level to grade

Revision ID: 5057b1ec9be6
Revises: 1ee7e0adc5a4
Create Date: 2025-04-30 19:13:31.490150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5057b1ec9be6'
down_revision: Union[str, None] = '1ee7e0adc5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('grade', sa.String(), nullable=False))
    op.drop_column('users', 'level')
    op.add_column('vacancies', sa.Column('grade', sa.String(), nullable=False))
    op.drop_column('vacancies', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('vacancies', 'grade')
    op.add_column('users', sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'grade')
    # ### end Alembic commands ###
