"""unique roadmaps for both

Revision ID: 75057d37a996
Revises: d690215ccd83
Create Date: 2025-05-03 21:55:23.619574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75057d37a996'
down_revision: Union[str, None] = 'd690215ccd83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roadmaps_grade_key', 'roadmaps', type_='unique')
    op.drop_constraint('roadmaps_specialization_key', 'roadmaps', type_='unique')
    op.create_unique_constraint('_specialization_grade_uc', 'roadmaps', ['specialization', 'grade'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_specialization_grade_uc', 'roadmaps', type_='unique')
    op.create_unique_constraint('roadmaps_specialization_key', 'roadmaps', ['specialization'])
    op.create_unique_constraint('roadmaps_grade_key', 'roadmaps', ['grade'])
    # ### end Alembic commands ###
