"""is_dynamic parameter is nullable

Revision ID: 8c20d6d11fa2
Revises: 0af1d5ef66e6
Create Date: 2025-05-10 15:42:22.649019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c20d6d11fa2'
down_revision: Union[str, None] = '0af1d5ef66e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roadmaps', 'is_dynamic',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roadmaps', 'is_dynamic',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
