"""unique roadmaps for both

Revision ID: 8d12800405b0
Revises: 75057d37a996
Create Date: 2025-05-03 21:59:49.697252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d12800405b0'
down_revision: Union[str, None] = '75057d37a996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'roadmap_nodes', 'roadmaps', ['roadmap_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roadmap_nodes', type_='foreignkey')
    # ### end Alembic commands ###
