"""add url and employer_name to vacancy

Revision ID: d4b36a94c415
Revises: 41f7d8f03d02
Create Date: 2025-05-03 18:16:51.233916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b36a94c415'
down_revision: Union[str, None] = '41f7d8f03d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('employer_name', sa.String(), nullable=False))
    op.add_column('vacancies', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'url')
    op.drop_column('vacancies', 'employer_name')
    # ### end Alembic commands ###
