"""unique roadmaps

Revision ID: d690215ccd83
Revises: 7786c9b40843
Create Date: 2025-05-03 21:52:07.563245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd690215ccd83'
down_revision: Union[str, None] = '7786c9b40843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roadmaps', ['specialization'])
    op.create_unique_constraint(None, 'roadmaps', ['grade'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roadmaps', type_='unique')
    op.drop_constraint(None, 'roadmaps', type_='unique')
    # ### end Alembic commands ###
