"""add hh_id to Vacancy

Revision ID: e7788c579489
Revises: 0af1d5ef66e6
Create Date: 2025-06-03 19:05:54.562711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7788c579489'
down_revision: Union[str, None] = '0af1d5ef66e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roadmaps', 'is_dynamic',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('vacancies', sa.Column('hh_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'vacancies', ['hh_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='unique')
    op.drop_column('vacancies', 'hh_id')
    op.alter_column('roadmaps', 'is_dynamic',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
